class YelpBusinessDatasetSchema:
    business_id = 'business_id'
    name = 'name'
    address = 'address'
    city = 'city'
    state = 'state'
    postal_code = 'postal code'
    latitude = 'latitude'
    longitude = 'longitude'
    stars = 'stars'
    review_count = 'review_count'
    is_open = 'is_open'
    attributes = 'attributes'
    categories = 'categories'
    hours = 'hours'
