class YelpUserDatasetSchema:
    """Yelp user dataset schema"""
    user_id = "user_id"
    name = "name"
    review_count = "review_count"
    yelping_since = "yelping_since"
    friends = "friends"
    useful = "useful"
    funny = "funny"
    cool = "cool"
    fans = "fans"
    elite = "elite"
    average_stars = "average_stars"
    compliment_hot = "compliment_hot"
    compliment_more = "compliment_more"
    compliment_profile = "compliment_profile"
    compliment_cute = "compliment_cute"
    compliment_list = "compliment_list"
    compliment_note = "compliment_note"
    compliment_plain = "compliment_plain"
    compliment_cool = "compliment_cool"
    compliment_funny = "compliment_funny"
    compliment_writer = "compliment_writer"
    compliment_photos = "compliment_photos"
